services:
  - type: web
    name: telegrambot
    env: python
    buildCommand: chmod +x render-build.sh && ./render-build.sh && pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
